version: "3.7"

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: backend
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./fishData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Fish
      - DATABASE_URL=mongodb://db/fish
    ports:
      - 27017:27017
