name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    
    - name: Run the tests
      run: npm test -- --coverage
      uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: | 
            coverage/lcov.info
            test-report.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
          token: ${{ secrets.CODECOV_TOKEN_USER }}